" Configuration initiale de Vim
set nocompatible
syntax on
filetype plugin indent on

" Gestionnaire de plugins
call plug#begin()
" Plugins essentiels
Plug 'sheerun/vim-polyglot'
Plug 'Yggdroot/indentLine'
Plug 'morhetz/gruvbox'
call plug#end()

" Configuration de base
set cursorline
set encoding=utf-8
set hidden
set number
set relativenumber
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set mouse=a
set nowrap
set ignorecase
set smartcase
set incsearch
set hlsearch
set history=1000
set undolevels=1000

" Configuration des thèmes et couleurs
if has('termguicolors')
    set termguicolors
endif

" Configuration de Gruvbox
set background=dark
let g:gruvbox_contrast_dark = 'medium'
let g:gruvbox_italic=1
let g:gruvbox_bold=1
let g:gruvbox_underline=1
let g:gruvbox_undercurl=1
let g:gruvbox_sign_column='bg0'

" Active le thème custom par défaut
autocmd vimenter * ++nested colorscheme custom_theme


" Configuration spécifique pour certains types de fichiers
augroup gruvbox_customization
    autocmd!
    autocmd FileType python let g:gruvbox_improved_strings=1
augroup END






" Configuration des espaces et tabs visibles
set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.

" Configuration de IndentLine
let g:indentLine_char = '¦'
let g:indentLine_color_term = 239


" Sauvegarde automatique
set autowrite
set autowriteall


set nobackup
set noswapfile
set nowritebackup
